#
# https://www.sylvaindurand.org/making-jekyll-multilingual/
#
title: 
 de: ChainSquad.de GmbH
 en: ChainSquad.com GmbH
email: info@chainsquad.com
name: ChainSquad GmbH
vision: 
 de: >
  Die autonome Blockketten-Technologie Ã¤ndert alles.
 en: >
  The autonomous blockchain technology is yet to disrupt.
baseurl: ""
url: "http://chainsquad.com"
github: chainsquad
markdown: kramdown
excerpt_separator: <!--more-->

collections:
 clients:
   output: false
 chains:
   output: false
 presentations:
   output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  posts_limit: 20

nav:
  - url: /contact
    icon: "ğŸ“¯"
    ref: "Contact"
    lang: en

  - url: /services
    icon: "ğŸ—"
    ref: Services
    lang: en

  - url: /presentations
    icon: "ğŸ“Š"
    ref: Presentations
    lang: en

  - url: https://articles.chainsquad.com
    icon: ğŸ–‡
    ref: Articles
    lang: en
